version: '2'

networks:
    laravel:


services:
    site:
        build:
            context: ./docker
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: nginx_aodabong
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mariadb:10.6
        container_name: mysql_aodabong
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: aodabong
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php_aodabong
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - laravel
